name: CD Pipeline - Deploy to GCP Cloud Run

on:
  workflow_run:
    workflows: ["CI Pipeline - Scan with SonarCloud, Build Image, Push to Docker Hub."] 
    types:
      - completed
    branches:
      - main 

env:
  DOCKERHUB_IMAGE_NAME: ${{ github.event.workflow_run.repository.name }} 

  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: 'asia-southeast1' 
  GCP_CLOUD_RUN_SERVICE_TESTING: 'calendar-testing' 
  GCP_CLOUD_RUN_SERVICE_PRODUCTION: 'calendar-production' 

jobs:
  deploy-testing:
    name: 🚀 Deploy to GCP Testing
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read   
      id-token: write  

    environment:
      name: testing

    steps:
      - name: ⬇️ Checkout code at specific commit from CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: 🔑 Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL_ID }}/providers/${{ secrets.GCP_WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: 🚀 Deploy to Cloud Run (Testing)
        id: deploy_testing_step
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE_TESTING }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          region: ${{ env.GCP_REGION }}
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}

  approve-production:
    name: 👍 Approve for Production Deployment
    needs: deploy-testing
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: production-approval 
      
    steps:
      - name: Manual Approval Required
        run: echo "Menunggu approval untuk deployment ke Produksi via GitHub Environments."

  deploy-production:
    name: 🚢 Deploy to GCP Production
    needs: approve-production
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    environment:
      name: production

    steps:
      - name: ⬇️ Checkout code at specific commit from CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: 🔑 Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL_ID }}/providers/${{ secrets.GCP_WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_PRODUCTION }}' 

      - name: 🚀 Deploy to Cloud Run (Production)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE_PRODUCTION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          region: ${{ env.GCP_REGION }}
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
